# Generated by Django 2.2 on 2023-01-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyonline', '0002_auto_20230113_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
