# Generated by Django 2.2 on 2023-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyonline', '0003_auto_20230114_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
